export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'

export const CONFIGURE = 'CONFIGURE'
export const CONFIGURE_RETURNED = 'CONFIGURE_RETURNED'

export const CHANINID_RETURNED = 'CHANINID_RETURNED'

export const APPROVE = 'APPROVE'
export const APPROVE_RETURNED = 'APPROVE_RETURNED'

export const APPROVEDFK = 'APPROVEDFK'
export const APPROVEDFK_RETURNED = 'APPROVEDFK_RETURNED'

export const APPDFKIIROVEDFK = 'APPDFKIIROVEDFK'
export const APPDFKIIROVEDFK_RETURNED = 'APPDFKIIROVEDFK_RETURNED'

export const APPUSDTROVEDFK = 'APPUSDTROVEDFK'
export const APPUSDTROVEDFK_RETURNED = 'APPUSDTROVEDFK_RETURNED'

export const APPSELLROVEDFK = 'APPSELLROVEDFK'
export const APPSELLROVEDFK_RETURNED = 'APPSELLROVEDFK_RETURNED'

export const STAKEDFK = 'STAKEDFK'
export const STAKEDFK_RETURNED = 'STAKEDFK_RETURNED'

export const STAKEDFKUSDT = 'STAKEDFKUSDT'
export const STAKEDFKUSDT_RETURNED = 'STAKEDFKUSDT_RETURNED'

export const STAKEUSDTDFK = 'STAKEUSDTDFK'
export const STAKEUSDTDFK_RETURNED = 'STAKEUSDTDFK_RETURNED'

export const GETDFK_REWARDS = 'GETDFK_REWARDS'
export const GETDFK_REWARDS_RETURNED = 'GETDFK_REWARDS'

export const EXITDFK = 'EXITDFK'
export const EXITDFK_RETURNED = 'EXITDFK_RETURNED'

export const EXITUSDTDFK = 'EXITUSDTDFK'
export const EXITUSDTDFK_RETURNED = 'EXITUSDTDFK_RETURNED'

export const GET_BALANCES = 'GET_BALANCES'
export const GET_BALANCES_RETURNED = 'GET_BALANCES_RETURNED'

export const GET_CLAIMABLE = 'GET_CLAIMABLE'
export const GET_CLAIMABLE_RETURNED = 'GET_CLAIMABLE_RETURNED'

export const GET_YCRV_REQUIREMENTS = 'GET_YCRV_REQUIREMENTS'
export const GET_YCRV_REQUIREMENTS_RETURNED = 'GET_YCRV_REQUIREMENTS_RETURNED'


// BXH start
export const GET_BXHList_PERPETUAL = 'GET_BXHList_PERPETUAL'
export const GET_BXHList_PERPETUAL_RETURNED = 'GET_BXHList_PERPETUAL_RETURNED'

export const GET_BXHEXCHANGE_PERPETUAL = 'GET_BXHEXCHANGE_PERPETUAL'
export const GET_BXHEXCHANGE_PERPETUAL_RETURNED = 'GET_BXHEXCHANGE_PERPETUAL_RETURNED'

export const GET_PASSEXCHANGE_PERPETUAL = 'GET_PASSEXCHANGE_PERPETUAL'
export const GET_PASSEXCHANGE_PERPETUAL_RETURNED = 'GET_PASSEXCHANGE_PERPETUAL_RETURNED'
export const GET_PASSEXCHANGE_REFRESH = 'GET_PASSEXCHANGE_REFRESH'

export const STAKESYMBOLTOKNES = 'STAKESYMBOLTOKNES'
export const STAKESYMBOLTOKNES_RETURNED = 'STAKESYMBOLTOKNES_RETURNED'

export const APPEXCHANGETOKENS = 'APPEXCHANGETOKENS'
export const APPEXCHANGETOKENS_RETURNED = 'APPEXCHANGETOKENS_RETURNED'

export const GET_WRAPTOKENS = 'GET_WRAPTOKENS'
export const GET_WRAPTOKENS_RETURNED = 'GET_WRAPTOKENS_RETURNED'

export const GET_TOKENBALANCEANOUNT = "GET_TOKENBALANCEANOUNT"
export const GET_TOKENBALANCEANOUNT_RETURNED = "GET_TOKENBALANCEANOUNT_RETURNED"

export const GET_BXHTRADESTAKEINIT = "GET_BXHTRADESTAKEINIT"
export const GET_BXHTRADESTAKEINIT_RETURNED = "GET_BXHTRADESTAKEINIT_RETURNED"

export const GET_BXHTRADESTAKEApprove = "GET_BXHTRADESTAKEApprove"
export const GET_BXHTRADESTAKEApprove_RETURNED = "GET_BXHTRADESTAKEApprove_RETURNED"

export const GET_BXHTRADESTAKEApprove1 = "GET_BXHTRADESTAKEApprove1"
export const GET_BXHTRADESTAKEApprove1_RETURNED = "GET_BXHTRADESTAKEApprove1_RETURNED"

export const BXHADDLIQUIDITY = "BXHADDLIQUIDITY"
export const BXHADDLIQUIDITY_RETURNED = "BXHADDLIQUIDITY_RETURNED"

export const BXHREMOVELIQUIDITY = "BXHREMOVELIQUIDITY"
export const BXHREMOVELIQUIDITY_RETURNED = "BXHREMOVELIQUIDITY_RETURNED"

export const BXHCALCULATION = "BXHCALCULATION"
export const BXHCALCULATION_RETURNED = "BXHCALCULATION_RETURNED"
export const BXHCALCULATION2 = "BXHCALCULATION2"
export const BXHCALCULATION2_RETURNED = "BXHCALCULATION2_RETURNED"

export const GET_SYMBOL_RETURNED = "GET_SYMBOL_RETURNED"

export const APPALLOWANCE = 'APPALLOWANCE'
export const APPALLOWANCE_RETURNED = 'APPALLOWANCE_RETURNED'
export const APPSWAPALLOWANCE = 'APPSWAPALLOWANCE'

export const BXHALLOWANCEREMOVELIQUIDITY = "BXHALLOWANCEREMOVELIQUIDITY"
export const BXHALLOWANCEREMOVELIQUIDITY_RETURNED = "BXHCALCULATION_RETURNED"

export const BXHLISTBALANCEHOME = "BXHLISTBALANCEHOME"
export const BXHLISTBALANCEHOME_RETURNED = "BXHLISTBALANCEHOME_RETURNED"

export const BXHPAGEREFRESH_RETURN = "BXHPAGEREFRESH_RETURN"

export const SEARCHSYBMOL = "SEARCHSYBMOL"
export const SEARCHSYBMOL_RETURNED = "SEARCHSYBMOL_RETURNED"

export const BXHDAOUSERINFO = "BXHDAOUSERINFO"
export const BXHDAOUSERINFO_RETURNED = "BXHDAOUSERINFO_RETURNED"

export const BXHDAOUSERPending = "BXHDAOUSERPending"//未领取收益
export const BXHDAOUSERPending_RETURNED = "BXHDAOUSERPending_RETURNED"

export const BXHDAOTRADESTAKEApprove = "BXHDAOTRADESTAKEApprove"//dao质押授权
export const BXHDAOTRADESTAKEApprove_RETURNED = "BXHDAOTRADESTAKEApprove_RETURNED"

export const BXHDAOBXHDeposit = "BXHDAOBXHDeposit"//BXH质押dao
export const BXHDAOBXHDeposit_RETURNED = "BXHDAOBXHDeposit_RETURNED"

export const BXHDAOBXHRetrieve = "BXHDAOBXHRetrieve"//BXH取回dao
export const BXHDAOBXHRetrieve_RETURNED = "BXHDAOBXHRetrieve_RETURNED"

export const BXHDAOLockupApprove = "BXHDAOLockupApprove"//dao锁仓授权
export const BXHDAOLockupApprove_RETURNED = "BXHDAOLockupApprove_RETURNED"

export const BXHDAOBXHLockUpDeposit = "BXHDAOBXHLockUpDeposit"//锁仓BXH质押dao
export const BXHDAOBXHLockUpDeposit_RETURNED = "BXHDAOBXHLockUpDeposit_RETURNED"

export const BXHDAOBXHLockUpRetrieve = "BXHDAOBXHLockUpRetrieve"//锁仓BXH取回dao
export const BXHDAOBXHLockUpRetrieve_RETURNED = "BXHDAOBXHLockUpRetrieve_RETURNED"

//DaoV2
export const BXHDAOV2PledgeApprove = "BXHDAOV2PledgeApprove"//dao质押授权
export const BXHDAOV2PledgeApprove_RETURNED = "BXHDAOV2PledgeApprove_RETURNED"

export const BXHDAOV2BXHDeposit = "BXHDAOV2BXHDeposit"//BXH质押dao
export const BXHDAOV2BXHDeposit_RETURNED = "BXHDAOV2BXHDeposit_RETURNED"

export const BXHDAOV2BXHRetrieve = "BXHDAOV2BXHRetrieve"//BXH取回dao
export const BXHDAOV2BXHRetrieve_RETURNED = "BXHDAOV2BXHRetrieve_RETURNED"

export const BXHDAOBXHClaim = "BXHDAOBXHClaim"//BXH领取
export const BXHDAOBXHClaim_RETURNED = "BXHDAOBXHClaim_RETURNED"

export const BXHDAOBXHUnStake = "BXHDAOBXHUnStake"//BXH提取质押
export const BXHDAOBXHUnStake_RETURNED = "BXHDAOBXHUnStake_RETURNED"

export const BXHDAOBXHTeamRewards = "BXHDAOBXHTeamRewards"//BXH领取团队奖励
export const BXHDAOBXHTeamRewards_RETURNED = "BXHDAOBXHTeamRewards_RETURNED"

//DaoV3
export const BXHDAOV3PledgeApprove = "BXHDAOV3PledgeApprove"//dao质押授权
export const BXHDAOV3PledgeApprove_RETURNED = "BXHDAOV3PledgeApprove_RETURNED"

export const BXHDAOV3PledgeXBXHApprove = "BXHDAOV3PledgeXBXHApprove"//dao质押XBXH授权
export const BXHDAOV3PledgeXBXHApprove_RETURNED = "BXHDAOV3PledgeXBXHApprove_RETURNED"

export const BXHDAOV3BXHDeposit = "BXHDAOV3BXHDeposit"//BXH质押dao
export const BXHDAOV3BXHDeposit_RETURNED = "BXHDAOV3BXHDeposit_RETURNED"

export const BXHDAOV3BXHRetrieve = "BXHDAOV3BXHRetrieve"//BXH取回dao
export const BXHDAOV3BXHRetrieve_RETURNED = "BXHDAOV3BXHRetrieve_RETURNED"

export const BXHDAOV3XBXHDeposit = "BXHDAOV3XBXHDeposit"//XBXH质押dao
export const BXHDAOV3XBXHDeposit_RETURNED = "BXHDAOV3XBXHDeposit_RETURNED"

export const BXHDAOV3XBXHRetrieve = "BXHDAOV3XBXHRetrieve"//XBXH取回dao
export const BXHDAOV3XBXHRetrieve_RETURNED = "BXHDAOV3XBXHRetrieve_RETURNED"

export const BXHDAOV3BXHClaim = "BXHDAOV3BXHClaim"//领取
export const BXHDAOV3BXHClaim_RETURNED = "BXHDAOV3BXHClaim_RETURNED"

//燃烧挖矿
export const BXHCombustionApprove = "BXHCombustionApprove"//抵押授权
export const BXHCombustionApprove_RETURNED = "BXHCombustionApprove_RETURNED"

export const BXHCombustionDeposit = "BXHCombustionDeposit"//抵押
export const BXHCombustionDeposit_RETURNED = "BXHCombustionDeposit_RETURNED"

export const BXHCombustionWithdraw = "BXHCombustionWithdraw"//领取收益
export const BXHCombustionWithdraw_RETURNED = "BXHCombustionWithdraw_RETURNED"

//借贷
export const BXHLoanClaim_RETURN = "BXHLoanClaim_RETURN"//领取用户奖励
export const BXHLoanDeposit_RETURN = "BXHLoanDeposit_RETURN"//授权

//造星计划
export const BXHStarPlanApprove = "BXHStarPlanApprove"//授权
export const BXHStarPlanApprove_RETURNED = "BXHCombustionApprove_RETURNED"

export const BXHStarPlanVote = "BXHStarPlanVote"//Vote
export const BXHStarPlanVote_RETURNED = "BXHStarPlanVote_RETURNED"

export const BXHStarPlanWithdraw = "BXHStarPlanWithdraw"//领取收益
export const BXHStarPlanWithdraw_RETURNED = "BXHStarPlanWithdraw_RETURNED"

export const BXHCALUTOKENAMOUNT = "BXHCALUTOKENAMOUNT"
export const BXHCALUTOKENAMOUNT_RETURNED = "BXHCALUTOKENAMOUNT_RETURNED"

export const BXHBALANCE_RETURNED = "BXHBALANCE_RETURNED"

export const BXHCOOKIEREFRESHEVENT = "BXHCOOKIEREFRESHEVENT"

export const BXHGETAIRDROP = "BXHGETAIRDROP"
export const BXHGETAIRDROP_RETURNED = "BXHGETAIRDROP_RETURNED"

export const BXHYIELDGETAIRDROP = "BXHYIELDGETAIRDROP" //查询是否领取过空投
export const BXHYIELDGETAIRDROP_RETURNED = "BXHYIELDGETAIRDROP_RETURNED"

export const BXHGETPAIRBYTOKENS = "BXHGETPAIRBYTOKENS"//通过token0和token1地址获取流动吃是否存在
export const BXHGETPAIRBYTOKENS_RETURNED = "BXHGETPAIRBYTOKENS_RETURNED"

export const BXHCREATELIQUIDITYPOOL = "BXHCREATELIQUIDITYPOOL"//创建资金池
export const BXHCREATELIQUIDITYPOOL_RETURNED = "BXHCREATELIQUIDITYPOOL_RETURNED"

export const BXHSWAPSYBMOL = "BXHSWAPSYBMOL"
export const BXHSWAPSYBMOL_RETURNED = "BXHSWAPSYBMOL_RETURNED"

export const BXHGETPOOLINFOBYID = "BXHGETPOOLINFOBYID"
export const BXHGETPOOLINFOBYID_RETURNED = "BXHGETPOOLINFOBYID_RETURNED"

export const BXHUSDTGETPOOLINFOBYID = "BXHUSDTGETPOOLINFOBYID"
export const BXHUSDTGETPOOLINFOBYID_RETURNED = "BXHUSDTGETPOOLINFOBYID_RETURNED"

export const BXHSINGLETOKENINFO = "BXHSINGLETOKENINFO"
export const BXHSINGLETOKENINFO_RETURNED = "BXHSINGLETOKENINFO_RETURNED"

export const BXHGETSINGLEPOOLINFOBUID = "BXHGETSINGLEPOOLINFOBUID"
export const BXHGETSINGLEPOOLINFOBUID_RETURNED = "BXHGETSINGLEPOOLINFOBUID_RETURNED"

export const BXHCHNAGEACCOUNT = "BXHCHNAGEACCOUNT"
export const BXHCHNAGEACCOUNT_RETURN = "BXHCHNAGEACCOUNT_RETURN"

export const BXH_HOMEBALANCE = "BXH_HOMEBALANCE"
export const BXH_HOMEBALANCE_RETURNED = "BXH_HOMEBALANCE_RETURNED"

export const BXHCENTERINFOUPDATEINFO = "BXHCENTERINFOUPDATEINFO"

export const GET_BXHTWIST = "GET_BXHTWIST"
export const GET_BXHTWIST_RETURNED = "GET_BXHTWIST_RETURNED"

export const GET_BXHDEPOSITTWIST = "GET_BXHDEPOSITTWIST"
export const GET_BXHDEPOSITTWIST_RETURNED = "GET_BXHDEPOSITTWIST_RETURNED"

export const GET_TWISTALLOWANCE = "GET_TWISTALLOWANCE"
export const GET_TWISTALLOWANCE_RETURNED = "GET_TWISTALLOWANCE_RETURNED"

export const GET_TWISTALLOWANCE1 = "GET_TWISTALLOWANCE1"
export const GET_TWISTALLOWANCE_RETURNED1 = "GET_TWISTALLOWANCE_RETURNED1"

export const GET_TWISTCANCEL = "GET_TWISTCANCEL"
export const GET_TWISTCANCEL_RETURNED = "GET_TWISTCANCEL_RETURNED"

export const GET_TWISTPLEDGE = "GET_TWISTPLEDGE"
export const GET_TWISTPLEDGE_RETURNED = "GET_TWISTPLEDGE_RETURNED"

export const GET_TWISTPLEDGECANCEL = "GET_TWISTPLEDGECANCEL"
export const GET_TWISTPLEDGECANCEL_RETURNED = "GET_TWISTPLEDGECANCEL_RETURNED"

export const GET_TWISTPOOLINFOBYID = "GET_TWISTPOOLINFOBYID"
export const GET_TWISTPOOLINFOBYID_RETURNED = "GET_TWISTPOOLINFOBYID_RETURNED"

export const GET_PLEDGEPOOLINFOBYID = "GET_PLEDGEPOOLINFOBYID"
export const GET_PLEDGEPOOLINFOBYID_RETURNED = "GET_PLEDGEPOOLINFOBYID_RETURNED"

export const GET_USDTPLEDGEPOOLINFOBYID = "GET_USDTPLEDGEPOOLINFOBYID"
export const GET_USDTPLEDGEPOOLINFOBYID_RETURNED = "GET_USDTPLEDGEPOOLINFOBYID_RETURNED"

export const STAKEBXH = "STAKEBXH"
export const STAKEBXH_RETURNED = "STAKEBXH_RETURNED"

export const STAKEBXH_CHAINID = "STAKEBXH_CHAINID"
export const STAKEBXH_CHAINID_RETURNED = "STAKEBXH_CHAINID_RETURNED"

export const GET_LOANBORROWBALANCE = "GET_LOANBORROWBALANCE"
export const GET_LOANBORROWBALANCE_RETURNED = "GET_LOANBORROWBALANCE_RETURNED"

export const GET__BXHBRIDGEMAIN = "GET__BXHBRIDGEMAIN"
export const GET__BRIDGEMAINRETURNED = "GET__BRIDGEMAINRETURNED"

export const GET_TOKENPRICE_RETURNED = "GET_TOKENPRICE_RETURNED"
export const GET_TOKENPAYPRICE_RETURNED = "GET_TOKENPAYPRICE_RETURNED"

export const GET_XDTALLOWANCE = "GET_XDTALLOWANCE"
export const GET_XDTALLOWANCE_RETURNED = "GET_XDTALLOWANCE_RETURNED"

export const GET_XDTSTATRE = "GET_XDTSTATRE"
export const GET_XDTSTATRE_RETURNED = "GET_XDTSTATRE_RETURNED"
export const GET_XDTSUCCEE_RETURNED = "GET_XDTSUCCEE_RETURNED"

export const GET_XTOKENPRICE = "GET_XTOKENPRICE"
export const GET_XTOKENPRICE_RETURNED = "GET_XTOKENPRICE_RETURNED"

export const GET_XTOKENSTATRE = "GET_XTOKENSTATRE"
export const GET_XTOKENSTATRE_RETURNED = "GET_XTOKENSTATRE_RETURNED"

export const GET_XTOKENALLOWANCE = "GET_XTOKENALLOWANCE"
// BXH end

//Single
export const SINGLETOKENAPPROVE = 'SINGLETOKENAPPROVE';
export const SINGLETOKENAPPROVE_RETURN = 'SINGLETOKENAPPROVE_RETURN';

export const SINGLETOKENDEPOSIT = 'SINGLETOKENDEPOSIT';
export const SINGLETOKENDEPOSIT_RETURN = 'SINGLETOKENDEPOSIT_RETURN';

export const SINGLETOKENWITHDRAW = 'SINGLETOKENWITHDRAW';
export const SINGLETOKENWITHDRAW_RETURN = 'SINGLETOKENWITHDRAW_RETURN';

export const SINGLETOKENWITHDRAWUNLOCK = 'SINGLETOKENWITHDRAWUNLOCK';
export const SINGLETOKENWITHDRAWUNLOCK_RETURN = 'SINGLETOKENWITHDRAWUNLOCK_RETURN';

export const SINGLETOKENCLAIMREWARD = 'SINGLETOKENCLAIMREWARD';
export const SINGLETOKENCLAIMREWARD_RETURN = 'SINGLETOKENCLAIMREWARD_RETURN';

export const SINGLEXTOKENAPPROVE = 'SINGLEXTOKENAPPROVE';
export const SINGLEXTOKENAPPROVE_RETURN = 'SINGLEXTOKENAPPROVE_RETURN';

export const SINGLEXTOKENSTAKE = 'SINGLEXTOKENSTAKE';
export const SINGLEXTOKENSTAKE_RETURN = 'SINGLEXTOKENSTAKE_RETURN';

export const SINGLEXTOKENWITHDRAW = 'SINGLEXTOKENWITHDRAW';
export const SINGLEXTOKENWITHDRAW_RETURN = 'SINGLEXTOKENWITHDRAW_RETURN';

export const BXHBRIDGESTAKE_RETURN = "BXHBRIDGESTAKE_RETURN"

export const BXHMENUHEADER = "BXHMENUHEADER"
export const BXHMENUHEADER_RETURN = "BXHMENUHEADER_RETURN"

export const BXHINDEXBANNER = "BXHINDEXBANNER"
export const BXHINDEXBANNER_RETURN = "BXHINDEXBANNER_RETURN"

export const BXHINDEXNOTICE = "BXHINDEXNOTICE"
export const BXHINDEXNOTICE_RETURN = "BXHINDEXNOTICE_RETURN"

export const BXHSHOUYI_RETURN = "BXHSHOUYI_RETURN"

export const BXHTOKENLIST = "BXHTOKENLIST"
//EndSingle
